name: Publish ngx-toastr-message

# Trigger only on tags like v1.0.0
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (Angular 20+ requires Node >= 20.19)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      # Cache npm dependencies
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Clean node_modules only
      - name: Clean node_modules
        run: rm -rf node_modules

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Lint
      - name: Lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      # Build the library
      - name: Build ngx-toastr-message
        run: npm run build ngx-toastr-message

      # Publish to npm
      - name: Publish to npm
        run: cd dist/ngx-toastr-message && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Create GitHub release
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# name: Publish ngx-toastr-message

# # Trigger only on tags like v1.0.0
# on:
#   push:
#     tags:
#       - 'v*.*.*'

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:

#       # Checkout code
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Setup Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '18'  # stable for Angular builds
#           registry-url: 'https://registry.npmjs.org'

      # # Clean node_modules and package-lock.json
      # - name: Clean npm
      #   run: |
      #     rm -rf node_modules package-lock.json

#       # Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Build library
#       - name: Build ngx-toastr-message
#         run: npm run build ngx-toastr-message

#       # Publish to npm
#       - name: Publish to npm
#         run: cd dist/ngx-toastr-message && npm publish --access public
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
